# Generated by Django 5.2.7 on 2025-10-21 11:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Branch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Şube Adı')),
            ],
        ),
        migrations.CreateModel(
            name='Break',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.DateTimeField(auto_now_add=True, verbose_name='Başlangıç Zamanı')),
                ('end_time', models.DateTimeField(blank=True, null=True, verbose_name='Bitiş Zamanı')),
                ('branch', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.branch', verbose_name='Şube')),
                ('personnel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Personel')),
            ],
        ),
        migrations.CreateModel(
            name='Shift',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='Tarih')),
                ('shift_type', models.CharField(choices=[('SABAH', 'Sabahçı (07:30 - 16:30)'), ('ARACI', 'Aracı (11:30 - 20:30)'), ('AKSAM', 'Akşamcı (15:30 - 00:30)'), ('ETKINLIK', 'Etkinlik (Manuel Saat)'), ('IZIN', 'İzinli')], max_length=10, verbose_name='Vardiya Tipi')),
                ('start_time', models.DateTimeField(blank=True, null=True, verbose_name='Vardiya Başlangıç (Hesaplandı)')),
                ('end_time', models.DateTimeField(blank=True, null=True, verbose_name='Vardiya Bitiş (Hesaplandı)')),
                ('custom_start_time', models.TimeField(blank=True, null=True, verbose_name='Etkinlik Başlangıç Saati')),
                ('custom_end_time', models.TimeField(blank=True, null=True, verbose_name='Etkinlik Bitiş Saati')),
                ('branch', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.branch', verbose_name='Şube')),
                ('personnel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Personel')),
            ],
        ),
    ]
