# Generated by Django 5.2.7 on 2025-10-28 07:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Branch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Şube Adı')),
                ('slug', models.SlugField(blank=True, editable=False, max_length=120, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Break',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.DateTimeField(auto_now_add=True, verbose_name='Başlangıç Zamanı')),
                ('end_time', models.DateTimeField(blank=True, null=True, verbose_name='Bitiş Zamanı')),
                ('branch', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.branch', verbose_name='Şube')),
                ('personnel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Personel')),
            ],
        ),
        migrations.CreateModel(
            name='LeaveRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('request_type', models.CharField(choices=[('IZIN', 'Yıllık İzin / Ücretsiz İzin'), ('RAPOR', 'Sağlık Raporu')], max_length=10, verbose_name='Talep Tipi')),
                ('start_date', models.DateField(verbose_name='Başlangıç Tarihi')),
                ('end_date', models.DateField(verbose_name='Bitiş Tarihi')),
                ('reason', models.TextField(blank=True, verbose_name='Açıklama / Sebep')),
                ('status', models.CharField(choices=[('BEKLIYOR', 'Onay Bekliyor'), ('ONAYLANDI', 'Onaylandı'), ('REDDEDILDI', 'Reddedildi')], default='BEKLIYOR', max_length=10, verbose_name='Talep Durumu')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Oluşturma Zamanı')),
                ('processed_at', models.DateTimeField(blank=True, null=True, verbose_name='İşlem Zamanı')),
                ('manager_notes', models.TextField(blank=True, verbose_name='Yönetici Notu')),
                ('personnel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Talep Eden Personel')),
                ('processed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='processed_leave_requests', to=settings.AUTH_USER_MODEL, verbose_name='İşlemi Yapan Yönetici')),
            ],
            options={
                'verbose_name': 'İzin/Rapor Talebi',
                'verbose_name_plural': 'İzin/Rapor Talepleri',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('branch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.branch', verbose_name='Atandığı Şube')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Shift',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='Tarih')),
                ('shift_type', models.CharField(choices=[('SABAH', 'Sabahçı (07:30 - 16:30)'), ('ARACI', 'Aracı (11:30 - 20:30)'), ('AKSAM', 'Akşamcı (15:30 - 00:30)'), ('ETKINLIK', 'Etkinlik (Manuel Saat)'), ('FAZLA_MESAI', 'Fazla Mesai (Manuel Saat)'), ('IZIN', 'İzinli'), ('RAPORLU', 'Raporlu'), ('DEVAMSIZ', 'Devamsız')], max_length=15, verbose_name='Vardiya Tipi / Durum')),
                ('start_time', models.DateTimeField(blank=True, null=True, verbose_name='Vardiya Başlangıç (Hesaplandı)')),
                ('end_time', models.DateTimeField(blank=True, null=True, verbose_name='Vardiya Bitiş (Hesaplandı)')),
                ('custom_start_time', models.TimeField(blank=True, null=True, verbose_name='Manuel Başlangıç Saati')),
                ('custom_end_time', models.TimeField(blank=True, null=True, verbose_name='Manuel Bitiş Saati')),
                ('branch', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.branch', verbose_name='Şube')),
                ('personnel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Personel')),
            ],
        ),
    ]
